version: 2
jobs:
    build:
        docker:
            - image: circleci/openjdk:8-jdk
        working_directory: ~/repo
        environment:
            MAVEN_OPTS: -Xmx3200m
        steps:
            - checkout
            - run: mvn clean
            - run: mvn package
            - run: mvn install
            - run: mvn deploy -DmuleDeploy